### ISSUE TITLE
"$pid" command failing on initialize

### ISSUE THREAD

**Issue by mreedmdev** [profesorfalken/jPowerShell#56]
As a use of earlier version of jpowershell, I've upgraded to 3.0.1, but cannot seem to get off the ground.
When attempting to openSession() the line 168 in the PowerShell.inialize method fails with parsing the result of the $pid command.
   //Get and store the PID of the process
   this.pid = Long.valueOf(executeCommand("$pid").getCommandOutput());

Throws NumberFormatException
 I've tried configuring my own powershell (powershell-core) and the installed powershell v5 on the system. I've adjusted timeouts to give powershell more time to start since the executeCommand("$pid") is returning "" and hence a NumberFormatException is thrown calling openSession or openSession(myPowershellPath).

Used jpowershell.properties to set maxWait so that openSession is effected.
maxWait:30000

Have tried nearly every variant of simply calling openSession and it fails regardless as described.

      try(PowerShell powerShell = PowerShell.openSession()) {
        PowerShellResponse response = powerShell.
            executeScript(pathToScript);
        log.info("{}", response);
      }catch(Exception e) {
        log.error("{}", e.getMessage());
      }

Any help would be appreciated.
Thanks

**Comment by mreedmdev** [comment]
It seems that powershell is not getting launched, a timeout occurs and the response to the $pid command ends up being "" and this throws NumberFormatException. I've ensured that powershell is available either as the default 'powershell.exe' or a custom powershell installation.

**Comment by jflefebvre06** [comment]
Hello,

Same problem.

To reproduce, add a file "%USERPROFILE%\documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1"

with the content :

```
#$HOME\Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1

Write-Host "Loaded."

```

**Comment by profesorfalken** [comment]
Hello, 
Weird. Thanks for reporting it.
I will check this.

Best regards

**Comment by mreedmdev** [comment]
profesorfalken,
It does NOT occur when I issue the $PID command from a console. I get a normal response of the process id. This only occurs when using jpowershell as described in my original post(if it is clear, i hope).

Windows Powershell v5.0.10586.117 and
Powershell CORE v6.1.0

Thanks for your attention to this! I am happy to provide any more useful information. I have already update to your latest fix, but have not tested it yet. I will let you know.

Thanks!

**Comment by jflefebvre06** [comment]
@[profesorfalken](/profesorfalken) works fine with 3.0.2 thank you.

**Comment by profesorfalken** [comment]
@mreedmdev 
Thank you for your answer. Now I see the problem. It is very interesting. 
I think I know how to fix it. I will try to do it today so you will be able to use the 3.x version which includes the proper autocloseable.

Best regards

**Comment by profesorfalken** [comment]
A new 3.0.3 version is available. Can you check @mreedmdev ?

Thanks

**Comment by mreedmdev** [comment]
@profesorfalken - Yes, I will check immediately and let you know the result ASAP.

Thank You !

**Comment by mreedmdev** [comment]
@profesorfalken, 3.0.3 seems to exhibit similar results.
1)It seems that the result of starting the session is loading the profile which results in the message 
"Running MicrosoftPowerShell_profile.ps1... and this is getting picked up in the outputstream being parsed when the $pid command is issued.
2)When I manually run the exact command getting ran by openSession() in a console, this is the first message output to the console before a prompt is presented.
3)Then I run the $pid command manually and get expected pid.

As I think you have already figured out the buffer is not getting cleared prior to the $pid command getting issued and NumberFormatException is thrown trying to parse the profile load message concatenated with the pid from the $pid command ""Running MicrosoftPowerShell_profile.ps1...23432"

This is the powershell prompt input/output from manually taking the same steps the code takes.

`C:\>powershell.exe
Windows PowerShell
Copyright (C) 2015 Microsoft Corporation. All rights reserved.

Running MicrosoftPowerShell_profile.ps1...
C:\mreed
> $pid
17276
C:\mreed
>`

I think you are on the right track clearing the buffer prior to the $pid being issued, but my test of 3.0.3 show that the entire  "Running MicrosoftPowerShell_profile.ps1...23432" is still being parsed and throwing.

Mark

**Comment by mreedmdev** [comment]
@profesorfalken 
1)I have found that the profile that is loading has a line in the script
`Write-Host "Running MicrosoftPowerShell_profile.ps1..."`
So this is where that is coming from.

2)If I remove the line from the profile the $PID command is executed and parsed correctly! 

A couple of thoughts:
1) I am using the jpowershell.properties file to create longer waits since some configurations take longer to load powershell than others.
2)If the loading of the session does timeout there is still an NumberFormatException that is thrown because the result of the $PID command is "" empty string on a timeout and this still seems to occur on 3.0.3
3)Not sure if any users may have any Write-Host commands in any profile scripts, but this can cause the problem of the output being picked up in the buffer of the $PID command output and reproduces the NumberFormatException.

So at this point if I exclude the Write-Host and avoid an openSession() timeout, I am past the reported issue with 3.0.3.
Mark

**Comment by wortner** [comment]
3.0.3 is working. I checked the power shell folder, but it is empty so I don't need to take care about Write-Host. So far couple of times I have got `closeAndWait
WARNING: Powershell process cannot be closed. Session seems to be blocked`. It seems to be connected with some timeout setting and now I'm looking for way to set it.

**Comment by jflefebvre06** [comment]
@[profesorfalken](/profesorfalken) No way to execute command excluding powershell profile ? perhaps `-NoProfile ` option ?

**Comment by profesorfalken** [comment]
@mreedmdev this is exactly how I tested the fix for 3.0.3

-First, I created a profile file at **USER\Documents\WindowsPowerShell** called Microsoft.PowerShell_profile.ps1
-I have written inside: 
    Write-Host "Running MicrosoftPowerShell_profile.ps1..."
-After that, I have launch one test and I have seen that _executeCommand("$pid").getCommandOutput()_ returned:
    Running MicrosoftPowerShell_profile.ps1... 10562
-So I have added the clearOutput() method that clears the initial buffer before launching the first command.
-And after that, I had the good result: 
    10562

So the problem of write-host on profile should be totally fixed in 3.0.3.

I still have the profile file set in my system and all the tests pass without a single problem.
I cannot understand how that continued to generate a NumberFormatException in your case with the 3.0.3 version.

> 2)If the loading of the session does timeout there is still an NumberFormatException that is thrown because the result of the $PID command is "" empty string on a timeout and this still seems to occur on 3.0.3

I cannot understand how il can retour an emty string. Event in 3.0.2 that should be fixed. Are you sure you are using the 3.0.3 version?

Best regards

**Comment by profesorfalken** [comment]
@wortner 

Thanks to confirm that it works.

The `closeAndWait WARNING: Powershell process cannot be closed. Session seems to be blocked`. happens sometimes when the PowerShell console hangs (for example, if it has not finished to execute the command). 
This is why I have to take the PID at the initialization. In this cases I use this PID to kill the process and avoid 'zombie' processes in the background.
Maybe it happens that your command is a little bit long, so in that case you can simply give a little more of time. By default it waits 10 secs.

If you want to give more time:

    //Init
    Map<String, String> myConfig = new HashMap<>();
    myConfig.put("maxWait", "30000");
    response = powerShell.configuration(myConfig).executeCommand("Get-WmiObject Win32_BIOS");
    //Close

Best regards

**Comment by profesorfalken** [comment]
@jflefebvre06 

Thats a great idea!. Do you want to make me a Pull Request yourself or you prefer me to change it?

Best regards

**Comment by jflefebvre06** [comment]
@profesorfalken 
 Im out of office, could you please make the change

**Comment by profesorfalken** [comment]
v3.0.4 is published

**Comment by DipteshSavla** [comment]
Getting same issue on v3.1.0 for 
Powershell version 
Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      14393  1884

Best Regards

**Comment by dsagomonov** [comment]
Getting same issue on v3.1.0
java.lang.NumberFormatException: For input string: "﻿3784"
	at java.lang.NumberFormatException.forInputString(Unknown Source)
	at java.lang.Long.parseLong(Unknown Source)
	at java.lang.Long.valueOf(Unknown Source)
	at com.profesorfalken.jpowershell.PowerShell.initalize(PowerShell.java:168)
	at com.profesorfalken.jpowershell.PowerShell.openSession(PowerShell.java:129)
	at com.profesorfalken.jpowershell.PowerShell.openSession(PowerShell.java:108)
	at com.profesorfalken.wmi4java.WMIPowerShell.executeCommand(WMIPowerShell.java:42)
	at com.profesorfalken.wmi4java.WMIPowerShell.queryObject(WMIPowerShell.java:122)
	at com.profesorfalken.wmi4java.WMI4Java.getWMIObjectList(WMI4Java.java:332)

**Comment by jenskreidler** [comment]
> @wortner
> 
> Thanks to confirm that it works.
> 
> The `closeAndWait WARNING: Powershell process cannot be closed. Session seems to be blocked`. happens sometimes when the PowerShell console hangs (for example, if it has not finished to execute the command). This is why I have to take the PID at the initialization. In this cases I use this PID to kill the process and avoid 'zombie' processes in the background. Maybe it happens that your command is a little bit long, so in that case you can simply give a little more of time. By default it waits 10 secs.
> 
> If you want to give more time:
> 
> ```
> //Init
> Map<String, String> myConfig = new HashMap<>();
> myConfig.put("maxWait", "30000");
> response = powerShell.configuration(myConfig).executeCommand("Get-WmiObject Win32_BIOS");
> //Close
> ```
> 
> Best regards

Since Java 9+ we could get the PID directly from the [java.lang.Process#pid()](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/Process.html#pid()). We could get rid of the extra-Powershell call.
