### ISSUE TITLE
java.lang.NumberFormatException: For input string: "10136"

### ISSUE THREAD

**Issue by wortner** [profesorfalken/jPowerShell#57]
I have problem using 'Get-Process' with jPowerShell on Win 10 JDK 11 getting Number format error.
![image](https://user-images.githubusercontent.com/2852639/52194969-47e50280-2856-11e9-8ed8-95abce15c415.png). Nearly similar error I got using WMI4Java so I guess something wrong with my setup.

This is strange as the string contains additional data on the start (-1, -2 bytes).
![image](https://user-images.githubusercontent.com/2852639/52194894-ffc5e000-2855-11e9-82f4-97f9027b4aca.png)
Note: the process on which it fails seems always to be the powerShell process.

The stack trace is
`Exception in thread "main" java.lang.NumberFormatException: For input string: "﻿10136"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.base/java.lang.Long.parseLong(Long.java:692)
	at java.base/java.lang.Long.valueOf(Long.java:1144)
	at com.profesorfalken.jpowershell.PowerShell.initalize(PowerShell.java:168)
	at com.profesorfalken.jpowershell.PowerShell.openSession(PowerShell.java:129)
	at com.profesorfalken.jpowershell.PowerShell.openSession(PowerShell.java:108)
	at com.profesorfalken.jpowershell.PowerShell.executeSingleCommand(PowerShell.java:229)`

**Comment by profesorfalken** [comment]
Hello, 

I think this issue is related with #56. It is exactly the same line (PowerShell.java:168)

I close this one. Please follow #56 in order to get updates on the bug resolution.

Thanks and best regards
